# Generated by Django 2.0 on 2018-06-10 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='userNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=200)),
                ('note_detail', models.CharField(max_length=400)),
                ('due_date', models.DateField()),
                ('created_date', models.DateField(blank=True, default=datetime.date.today)),
                ('high_imp', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YourNotes.User')),
            ],
        ),
    ]
