# Generated by Django 2.0 on 2018-06-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YourNotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotes',
            old_name='user_name',
            new_name='usr_name',
        ),
    ]
