# Generated by Django 2.0 on 2018-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourNotes', '0003_auto_20180610_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email address'),
        ),
    ]
