# Generated by Django 2.0 on 2018-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourNotes', '0005_auto_20180610_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actual_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
