# Generated by Django 2.0 on 2018-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourNotes', '0006_auto_20180610_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='note_title',
            field=models.CharField(max_length=50),
        ),
    ]
