# Generated by Django 2.0 on 2018-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourNotes', '0010_auto_20180610_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='note_detail',
            field=models.CharField(max_length=200),
        ),
    ]
